### ISSUE TITLE
Can't execute the setup file

### ISSUE THREAD

**Issue by BragadeeshSA** [PPPLDeepLearning/plasma-python#35]
I have downloaded the project repository. I have navigated to the path where I have dowloaded the project files. When I tried executing 

python setup.py install

command I am getting the error 

![image](https://user-images.githubusercontent.com/49236167/55490877-2172f600-5652-11e9-9398-dfb49db2d790.png)

Kindly help me in this regard.

Thanks in Advance.

**Comment by ASvyatkovskiy** [comment]
@BragadeeshSA as the message suggests, you would need to first set up OpenMPI environment.
Steps to install OpenMPI are [here](https://www.open-mpi.org/faq/?category=building#easy-build)

**Comment by Airseai6** [comment]
the Windows system doesnot work？
