### ISSUE TITLE
the dataset can't be retrieved or can be viewed properly and no features can be visulaized 

### ISSUE THREAD

**Issue by shakthijayakumar** [PPPLDeepLearning/plasma-python#36]
hi sir,
       I am jayakumar working from india on plasma physics application for disruption prediction using machine learning and fuzzy techniques so,could you please help me to access the dataset to have a proper knowledge on dataset. i would like to express my willingness to work under you so please grant me access to utilise your dataset and i assure i will maintain ethical values.

**Comment by ASvyatkovskiy** [comment]
The plasma disruption datasets are owned by JET and D3D collaborations, we do not have permission to distribute the datasets at this time. We will work on providing sample datasets to help get started.
